/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-05-11 00:45:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Home : Sri Lanka Railways</title>\r\n");
      out.write("    <!--link css files-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/boostrap.min.css\">\r\n");
      out.write("    <!--link javascript fils-->\r\n");
      out.write("    <script src=\"./js/script.js\"></script>\r\n");
      out.write("    <script src=\"./js/icons.js\"></script>\r\n");
      out.write("    <!--boostrap css link-->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ\" crossorigin=\"anonymous\">\r\n");
      out.write("    <!--boostrap links-->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js\" integrity=\"sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!--animations-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/animate.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!--hed section-->\r\n");
      out.write("    <section id=\"header\">\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"navbar\"> <!--nav bar-->\r\n");
      out.write("          \r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("              <a class=\"navbar-brand\" href=\"#\" style=\"color:#fff;font-size: 40px;\"><img src=\"./imgs/logo-removebg-preview.png\" alt=\"\" width=\"100px\" height=\"100px\"></a>\r\n");
      out.write("              <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <i class=\"fa fa-bars\" aria-hidden=\"true\"></i>\r\n");
      out.write("              </button>\r\n");
      out.write("              <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("                <ul class=\"navbar-nav\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\"  href=\"#top\">Home</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#about\">About Us</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#servicea\">Services</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#famous\">Feactures</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#testimonials\">Reviwes</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#footer\">Contact Us</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </nav>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!--wellcome text-->\r\n");
      out.write("    <section id=\"wellcome\"  >\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"wellcome text-center wow slideInLeft\">\r\n");
      out.write("          <h1>Wellcome To Railway Resavation</h1>\r\n");
      out.write("          <p>On its path to Europe and the global market, coffee was transported by rail in Sri Lanka in 1864 from plantations in the Kandy area of the country's hills to the port city of Colombo. \r\n");
      out.write("            As a result of the 1871 coffee blight, many beautiful plantations were lost, and tea took their place.</p>\r\n");
      out.write("          <button type=\"submit\" class=\"main_btn\" onclick=\"location.href='../SignUp/login.jsp'\">Reserva Now</button>  \r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!--about us-->\r\n");
      out.write("    <section id=\"about\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <!--col1-->\r\n");
      out.write("          <div class=\"col-md-6 text-center\">\r\n");
      out.write("            <img src=\"./imgs/about_img.jpg\" class=\"img-fluid\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <!--col2-->\r\n");
      out.write("          <div class=\"col-md-6 text-justify\">\r\n");
      out.write("            <h3>About Our Service Hestory</h3>\r\n");
      out.write("            <p>Service began in 1864 with the construction of the Main Line from Colombo to Ambepussa, 54 kilometres (34 mi) east, and the first train ran on 27 December 1864. The line was officially opened to traffic on 2 October 1865.</p>\r\n");
      out.write("            <p>To serve the coconut plantations flourishing in the west, south west and north west coastal areas of the country, and the wet inland rubber plantations below the tea belt, railway lines were built in the wake of these agricultural developments. Thereafter, the need for cheap and safe travel in order to open up the hinterland of the country led to the expansion of the railway.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!--col3-->\r\n");
      out.write("          <div class=\"col-md-6 text-justify\">\r\n");
      out.write("            <h3>Our History</h3>\r\n");
      out.write("            <p>The Sri Lankan Railways formerly known as the Ceylon Government Railways has an eventful history of 150 years from the day the possibility of having a railways line from Colombo to Kandy and beyond was first discussed.By 1842, the necessity of the railway track was identified by the colonial rulers as the road alone was providing inadequate transport for coffee as there were not sufficient bullock carts or bullocks available.</p>\r\n");
      out.write("            <p>The history of Indian Railways dates back to over 160 years ago. On 16th April 1853, the first passenger train ran between Bori Bunder (Bombay) and Thane, a distance of 34 km. It was operated by three locomotives, named Sahib, Sultan and Sindh, and had thirteen carriages..</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!--col4-->\r\n");
      out.write("          <div class=\"col-md-6 text-justify\">\r\n");
      out.write("            <div class=\"embed-responsive embed-responsive-16by9\">\r\n");
      out.write("              <iframe class=\"embed-responsive-item\" width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/hxITmHjOD-w\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!--services-->\r\n");
      out.write("    <section id=\"servicea\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <img src=\"./imgs/seat-removebg.png\" alt=\"\" width=\"100px\" height=\"80px\">\r\n");
      out.write("            <h4>Reserva Seats</h4>\r\n");
      out.write("            <p>You can reaseve seats from this website. You can select the class ,seat number ,seat type by using this website</p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <img src=\"./imgs/time-removebg-preview.png\" alt=\"\" width=\"90px\" height=\"80px\">\r\n");
      out.write("            <h4>Train timetables</h4>\r\n");
      out.write("            <p>You can reaseve seats from this website. You can select the class ,seat number ,seat type by using this website</p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <img src=\"./imgs/speed-removebg-preview.png\" alt=\"\" width=\"110px\" height=\"70px\">\r\n");
      out.write("            <h4>Train Avaliability</h4>\r\n");
      out.write("            <p>You can reaseve seats from this website. You can select the class ,seat number ,seat type by using this website</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!--famous destinations-->\r\n");
      out.write("    <section id=\"famous\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-6\">\r\n");
      out.write("            <img src=\"./imgs/st1.jpg\" alt=\"\" class=\"img-fluid\" style=\"border-radius: 10px;\" width=\"500px\" height=\"400px\">\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6\">\r\n");
      out.write("            <div class=\"famous-box\">\r\n");
      out.write("              <div class=\"famous-left\">\r\n");
      out.write("                <i class=\"fa fa-smile-o\" aria-hidden=\"true\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"famous-right\">\r\n");
      out.write("                <h4>Our Staff</h4>\r\n");
      out.write("                <p>We hava the owrld famous and fully trained staff  to provide our service</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"famous-box\">\r\n");
      out.write("              <div class=\"famous-left\">\r\n");
      out.write("                <i class=\"fa fa-train\" aria-hidden=\"true\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"famous-right\">\r\n");
      out.write("                <h4>Our Drivers</h4>\r\n");
      out.write("                <p>We hava the owrld famous and fully trained staff  to provide our service</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"famous-box\">\r\n");
      out.write("              <div class=\"famous-left\">\r\n");
      out.write("                <i class=\"fa fa-certificate\" aria-hidden=\"true\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"famous-right\">\r\n");
      out.write("                <h4>World Recomondations</h4>\r\n");
      out.write("                <p>We hava the owrld famous and fully trained staff  to provide our service</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!--testimonials-->\r\n");
      out.write("    <section id=\"testimonials\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <h1 class=\"text-center\">Ideas From Our Users</h1>\r\n");
      out.write("        <p class=\"text-center\">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iste eligendi labore officiis expedita iusto voluptatum modi eum dolore autem maiores, illo quo provident vitae.</p><br>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <p class=\"reawive\">\r\n");
      out.write("              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Odio atque exercitationem, \r\n");
      out.write("               <br> <i class=\"fa fa-twitter\" aria-hidden=\"true\"></i><span>  @sachin</span>\r\n");
      out.write("            </p>\r\n");
      out.write("            <img src=\"./imgs/user1.jpg\" alt=\"\">\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-4 middle\">\r\n");
      out.write("            <p class=\"reawive\">\r\n");
      out.write("              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Odio atque exercitationem, \r\n");
      out.write("               <br> <i class=\"fa fa-twitter\" aria-hidden=\"true\"></i><span>  @sachin</span>\r\n");
      out.write("            </p>\r\n");
      out.write("            <img src=\"./imgs/user2.jpg\" alt=\"\">\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <p class=\"reawive\">\r\n");
      out.write("              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Odio atque exercitationem, \r\n");
      out.write("               <br> <i class=\"fa fa-twitter\" aria-hidden=\"true\"></i><span>  @sachin</span>\r\n");
      out.write("            </p>\r\n");
      out.write("            <img src=\"./imgs/user3.jpg\" alt=\"\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!--subscribe-->\r\n");
      out.write("    <section id=\"subscribe\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"subscribe text-center\">\r\n");
      out.write("          <h3>Subscribe For latest Updates.!</h3>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, sequi?</p>\r\n");
      out.write("          <div class=\"input-group\">\r\n");
      out.write("            <input type=\"email\" name=\"\" id=\"\" class=\"form-control\" placeholder=\"Email\">\r\n");
      out.write("            <input type=\"submit\" value=\"Submit\" class=\"form-control\" >\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!--footer section-->\r\n");
      out.write("    <section id=\"footer\">\r\n");
      out.write("      <div class=\"container \">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-3\">\r\n");
      out.write("            <img src=\"./imgs/logo-removebg-preview.png\" alt=\"\" width=\"100px\" height=\"100px\" class=\"footer-logo\">\r\n");
      out.write("            <p>Lorem ipsum dolor sit amet facere odit earum neque ullam illum voluptatibus molestiae.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-3\">\r\n");
      out.write("            <h1>Feactures</h1>\r\n");
      out.write("            <p>Super Staff</p>\r\n");
      out.write("            <p>Super Trains</p>\r\n");
      out.write("            <p>Super Drivers</p>\r\n");
      out.write("            <p>Super Commiunicatord</p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-3\">\r\n");
      out.write("            <h1>Quick Contact</h1>\r\n");
      out.write("            <p><i class=\"fa fa-phone-square\"></i> +9476 271 200</p>\r\n");
      out.write("            <p><i class=\"fa fa-envelope\"></i> railway@yahoo.com</p>\r\n");
      out.write("            <p><i class=\"fa fa-home\"></i> No23,Colombo,Sri Lanka</p>\r\n");
      out.write("            <p><i class=\"fa fa-fax\" aria-hidden=\"true\"></i>fax : +22311234</p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-3\">\r\n");
      out.write("            <h1>Follow Us On</h1>\r\n");
      out.write("            <p><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i> @railwayLannka</p>\r\n");
      out.write("            <p><i class=\"fa fa-facebook\"></i> @railway</p>\r\n");
      out.write("            <p><i class=\"fa fa-linkedin\"></i> @railway</p>\r\n");
      out.write("            <p><i class=\"fa fa-youtube\"></i> @railway</p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div><hr>\r\n");
      out.write("        <p class=\"copyright text-center\">Made By : Sachin Uthpala</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!--smmoth scroll js-->\r\n");
      out.write("    <script src=\"./js/smooth-scroll.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("      var scroll = new SmoothScroll('a[href*=\"#\"]');\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <!---animatons-->\r\n");
      out.write("    <script src=\"./js/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"./js/wow.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("      new WOW().init();   \r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
